name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node & pnpm
        uses: volta-cli/action@v4

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm config get store-dir)"

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm -r build

      - name: Test
        run: |
          pnpm -r test
